/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Builds a search index from documents.
 *
 * Takes an array of documents and returns a serialized search index as JSON.
 */
export declare function buildSearchIndex(documents: Array<JsSearchDocument>): string

/**
 * Runs i18n checks on dictionaries against used translation keys.
 *
 * `dict_dir` is the path to the i18n directory with locale subdirectories.
 * `used_keys` is a list of translation keys found in source code.
 */
export declare function checkI18n(dictDir: string, usedKeys: Array<string>): I18NCheckResult

/** Extracts documented declarations from a JavaScript/TypeScript file using Oxc. */
export declare function extractFileDocs(filePath: string, includePrivate?: boolean | undefined | null): Array<JsSourceDocItem>

/**
 * Extracts searchable content from Markdown source.
 *
 * Parses the Markdown and extracts title, body text, headings, and code.
 */
export declare function extractSearchContent(source: string, id: string, url: string, options?: JsParserOptions | undefined | null): JsSearchDocument

/** Extracts HTML comment-based speaker notes from a slide source. */
export declare function extractSlideComments(source: string): JsExtractedSlideComments

/**
 * Extracts translation keys from a TypeScript/JavaScript source string.
 *
 * Finds calls like `t('key')` and `$t('key')`.
 */
export declare function extractTranslationKeys(source: string, filePath: string, functionNames?: Array<string> | undefined | null): Array<I18NKeyUsage>

/** Generates a print-friendly HTML shell for deck-wide PDF export. */
export declare function generateDeckPrintHtml(data: JsDeckPrintRenderData, theme?: JsSlideTheme | undefined | null): string

/**
 * Generates an OG image as SVG.
 *
 * This function generates an SVG representation of an OG image
 * that can be used for social media previews.
 */
export declare function generateOgImageSvg(data: JsOgImageData, config?: JsOgImageConfig | undefined | null): string

/** Generates the presenter-mode HTML shell for a slide page. */
export declare function generatePresenterHtml(data: JsSlideRenderData, theme?: JsSlideTheme | undefined | null): string

/** Generates the standalone HTML shell for a slide page. */
export declare function generateSlideHtml(data: JsSlideRenderData, theme?: JsSlideTheme | undefined | null): string

/** Generates SSG HTML page with navigation and search. */
export declare function generateSsgHtml(pageData: JsSsgPageData, navGroups: Array<JsSsgNavGroup>, config: JsSsgConfig): string

/** Result of i18n checking. */
export interface I18NCheckResult {
  /** All diagnostics. */
  diagnostics: Array<I18NDiagnostic>
  /** Number of errors. */
  errorCount: number
  /** Number of warnings. */
  warningCount: number
}

/** A single i18n diagnostic. */
export interface I18NDiagnostic {
  /** Severity: "error", "warning", or "info". */
  severity: string
  /** Diagnostic message. */
  message: string
  /** Related translation key, if any. */
  key?: string
  /** Related locale, if any. */
  locale?: string
}

/** A translation key usage found in source code. */
export interface I18NKeyUsage {
  /** The translation key. */
  key: string
  /** Source file path. */
  filePath: string
  /** Line number. */
  line: number
  /** Column number. */
  column: number
  /** End column number. */
  endColumn: number
}

/** Result of loading dictionaries. */
export interface I18NLoadResult {
  /** Number of locales loaded. */
  localeCount: number
  /** All locale tags. */
  locales: Array<string>
  /** Errors encountered during loading. */
  errors: Array<string>
}

/** Deck-level print shell render data for JavaScript. */
export interface JsDeckPrintRenderData {
  deckTitle: string
  deckDescription?: string
  pageWidth: string
  pageHeight: string
  slides: Array<JsPrintSlideRenderData>
}

/** Entry page configuration. */
export interface JsEntryPageConfig {
  /** Hero section. */
  hero?: JsHeroConfig
  /** Feature cards. */
  features?: Array<JsFeatureConfig>
}

/** Extracted slide comments result for JavaScript. */
export interface JsExtractedSlideComments {
  content: string
  notes: Array<string>
}

/** Feature card for entry page. */
export interface JsFeatureConfig {
  /** Icon - supports: "mdi:icon-name" (Iconify), image URL, or emoji. */
  icon?: string
  /** Feature title. */
  title: string
  /** Feature description. */
  details?: string
  /** Optional link. */
  link?: string
  /** Link text. */
  linkText?: string
}

/** Hero action for entry page. */
export interface JsHeroAction {
  /** Button theme: "brand" or "alt". */
  theme?: string
  /** Button text. */
  text: string
  /** Link URL. */
  link: string
}

/** Hero section configuration for entry page. */
export interface JsHeroConfig {
  /** Main title (large, gradient text). */
  name?: string
  /** Secondary text. */
  text?: string
  /** Tagline. */
  tagline?: string
  /** Optional notice shown in the hero. */
  notice?: JsHeroNotice
  /** Hero image. */
  image?: JsHeroImage
  /** Action buttons. */
  actions?: Array<JsHeroAction>
}

/** Hero image for entry page. */
export interface JsHeroImage {
  /** Image source URL. */
  src: string
  /** Light mode image source URL. */
  lightSrc?: string
  /** Dark mode image source URL. */
  darkSrc?: string
  /** Alt text. */
  alt?: string
  /** Image width. */
  width?: number
  /** Image height. */
  height?: number
}

/** Hero notice for entry page. */
export interface JsHeroNotice {
  /** Notice title. */
  title?: string
  /** Notice paragraphs. */
  body?: Array<string>
}

/** Locale information for the locale switcher. */
export interface JsLocaleInfo {
  /** BCP 47 locale tag. */
  code: string
  /** Display name. */
  name: string
  /** Text direction. */
  dir: string
}

export interface JsMarkdownLintDiagnostic {
  ruleId: string
  severity: string
  message: string
  line: number
  column: number
  endLine: number
  endColumn: number
  language?: string
  suggestions?: Array<string>
}

export interface JsMarkdownLintDictionaryOptions {
  words?: Array<string>
  byLanguage?: Array<JsMarkdownLintLanguageWords>
  ignoredWords?: Array<string>
}

export interface JsMarkdownLintLanguageWords {
  language: string
  words: Array<string>
}

export interface JsMarkdownLintOptions {
  languages?: Array<string>
  rules?: JsMarkdownLintRuleOptions
  dictionary?: JsMarkdownLintDictionaryOptions
}

export interface JsMarkdownLintResult {
  diagnostics: Array<JsMarkdownLintDiagnostic>
  errorCount: number
  warningCount: number
  infoCount: number
  maskedDocument: string
}

export interface JsMarkdownLintRuleOptions {
  duplicateHeadings?: boolean
  headingIncrement?: boolean
  maxConsecutiveBlankLines?: number
  repeatedPunctuation?: boolean
  repeatedWords?: boolean
  spellcheck?: boolean
  trailingSpaces?: boolean
}

/** OG image configuration for JavaScript. */
export interface JsOgImageConfig {
  /** Image width in pixels. */
  width?: number
  /** Image height in pixels. */
  height?: number
  /** Background color (hex). */
  backgroundColor?: string
  /** Text color (hex). */
  textColor?: string
  /** Title font size. */
  titleFontSize?: number
  /** Description font size. */
  descriptionFontSize?: number
}

/** OG image data for JavaScript. */
export interface JsOgImageData {
  /** Page title. */
  title: string
  /** Page description. */
  description?: string
  /** Site name. */
  siteName?: string
  /** Author name. */
  author?: string
}

/** Parsed Markdown slide deck for JavaScript. */
export interface JsParsedSlideDeck {
  frontmatter: string
  slides: Array<JsSlideSource>
}

/** Parser options for JavaScript. */
export interface JsParserOptions {
  /** Enable GFM extensions. */
  gfm?: boolean
  /** Enable footnotes. */
  footnotes?: boolean
  /** Enable task lists. */
  taskLists?: boolean
  /** Enable tables. */
  tables?: boolean
  /** Enable strikethrough. */
  strikethrough?: boolean
  /** Enable autolinks. */
  autolinks?: boolean
}

/** Print shell render data for a single slide. */
export interface JsPrintSlideRenderData {
  slideTitle: string
  slideContentHtml: string
  slideNumber: number
  slideCount: number
}

/** Search document for JavaScript. */
export interface JsSearchDocument {
  /** Unique document identifier. */
  id: string
  /** Document title. */
  title: string
  /** Document URL. */
  url: string
  /** Document body text. */
  body: string
  /** Document headings. */
  headings: Array<string>
  /** Code snippets. */
  code: Array<string>
}

/** Search options for JavaScript. */
export interface JsSearchOptions {
  /** Maximum number of results. */
  limit?: number
  /** Enable prefix matching. */
  prefix?: boolean
  /** Enable fuzzy matching. */
  fuzzy?: boolean
  /** Minimum score threshold. */
  threshold?: number
}

/** Search result for JavaScript. */
export interface JsSearchResult {
  /** Document ID. */
  id: string
  /** Document title. */
  title: string
  /** Document URL. */
  url: string
  /** Relevance score. */
  score: number
  /** Matched terms. */
  matches: Array<string>
  /** Content snippet. */
  snippet: string
}

/** Slide page render data for JavaScript. */
export interface JsSlideRenderData {
  deckTitle: string
  slideTitle: string
  slideDescription?: string
  slideContentHtml: string
  slideNotesHtml?: string
  slideNumber: number
  slideCount: number
  homeHref: string
  slideHref: string
  presenterHref?: string
  previousHref?: string
  nextHref?: string
  nextSlideHref?: string
}

/** A parsed slide source for JavaScript. */
export interface JsSlideSource {
  content: string
  notes: Array<string>
}

/** Slide theme configuration for JavaScript. */
export interface JsSlideTheme {
  aspectRatio?: string
  maxWidth?: string
  maxHeight?: string
  padding?: string
  surfaceRadius?: string
  codeBackground?: string
  builtinAnimations?: boolean
  canvasBackground?: string
  surfaceBackground?: string
  surfaceBorder?: string
  surfaceShadow?: string
  presenterSidebarBackground?: string
  fontSans?: string
  fontMono?: string
  colorText?: string
  colorTextMuted?: string
  colorPrimary?: string
  colorBorder?: string
  darkCanvasBackground?: string
  darkSurfaceBackground?: string
  darkSurfaceBorder?: string
  darkPresenterSidebarBackground?: string
  darkCodeBackground?: string
  darkColorText?: string
  darkColorTextMuted?: string
  darkColorPrimary?: string
  darkColorBorder?: string
}

/** Social links for JavaScript. */
export interface JsSocialLinks {
  /** GitHub URL. */
  github?: string
  /** Twitter/X URL. */
  twitter?: string
  /** Discord URL. */
  discord?: string
}

/** Source documentation item extracted from a JS/TS file. */
export interface JsSourceDocItem {
  name: string
  kind: string
  doc?: string
  jsdoc?: string
  sourcePath: string
  line: number
  endLine: number
  exported: boolean
  signature?: string
  params: Array<JsSourceDocParam>
  returnType?: string
  tags: Array<JsSourceDocTag>
}

/** Parameter documentation extracted from source code. */
export interface JsSourceDocParam {
  name: string
  typeAnnotation?: string
  optional: boolean
  defaultValue?: string
  description?: string
}

/** Raw JSDoc tag extracted from source code. */
export interface JsSourceDocTag {
  tag: string
  value: string
}

/** SSG configuration. */
export interface JsSsgConfig {
  /** Site name. */
  siteName: string
  /** Base URL path. */
  base: string
  /** OG image URL. */
  ogImage?: string
  /** Theme configuration. */
  theme?: JsThemeConfig
  /** Current locale for this page. */
  locale?: string
  /** Available locales for locale switcher. */
  availableLocales?: Array<JsLocaleInfo>
}

/** Navigation group for SSG. */
export interface JsSsgNavGroup {
  /** Group title. */
  title: string
  /** Navigation items. */
  items: Array<JsSsgNavItem>
}

/** Navigation item for SSG. */
export interface JsSsgNavItem {
  /** Display title. */
  title: string
  /** URL path. */
  path: string
  /** Full href. */
  href: string
}

/** Page data for SSG. */
export interface JsSsgPageData {
  /** Page title. */
  title: string
  /** Page description. */
  description?: string
  /** Page content HTML. */
  content: string
  /** Table of contents entries. */
  toc: Array<TocEntry>
  /** URL path. */
  path: string
  /** Entry page configuration (if layout: entry). */
  entryPage?: JsEntryPageConfig
}

/** Theme colors for JavaScript. */
export interface JsThemeColors {
  /** Primary accent color. */
  primary?: string
  /** Primary color on hover. */
  primaryHover?: string
  /** Background color. */
  background?: string
  /** Alternative background color. */
  backgroundAlt?: string
  /** Main text color. */
  text?: string
  /** Muted text color. */
  textMuted?: string
  /** Border color. */
  border?: string
  /** Code block background color. */
  codeBackground?: string
  /** Code block text color. */
  codeText?: string
}

/** Theme configuration for JavaScript. */
export interface JsThemeConfig {
  /** Light mode colors. */
  colors?: JsThemeColors
  /** Dark mode colors. */
  darkColors?: JsThemeColors
  /** Font configuration. */
  fonts?: JsThemeFonts
  /** Entry page configuration. */
  entryPage?: JsThemeEntryPage
  /** Layout configuration. */
  layout?: JsThemeLayout
  /** Header configuration. */
  header?: JsThemeHeader
  /** Footer configuration. */
  footer?: JsThemeFooter
  /** Social links configuration. */
  socialLinks?: JsSocialLinks
  /** Embedded HTML content at specific positions. */
  embed?: JsThemeEmbed
  /** Additional custom CSS. */
  css?: string
  /** Additional custom JavaScript. */
  js?: string
}

/** Embedded HTML content for specific positions. */
export interface JsThemeEmbed {
  /** Content to embed into `<head>`. */
  head?: string
  /** Content before header. */
  headerBefore?: string
  /** Content after header. */
  headerAfter?: string
  /** Content before sidebar navigation. */
  sidebarBefore?: string
  /** Content after sidebar navigation. */
  sidebarAfter?: string
  /** Content before main content. */
  contentBefore?: string
  /** Content after main content. */
  contentAfter?: string
  /** Content before footer. */
  footerBefore?: string
  /** Custom footer content. */
  footer?: string
}

/** Entry page theme configuration for JavaScript. */
export interface JsThemeEntryPage {
  /** Landing page presentation mode. */
  mode?: string
}

/** Theme fonts for JavaScript. */
export interface JsThemeFonts {
  /** Sans-serif font stack. */
  sans?: string
  /** Monospace font stack. */
  mono?: string
}

/** Theme footer for JavaScript. */
export interface JsThemeFooter {
  /** Footer message (supports HTML). */
  message?: string
  /** Copyright text (supports HTML). */
  copyright?: string
}

/** Theme header for JavaScript. */
export interface JsThemeHeader {
  /** Logo image URL. */
  logo?: string
  /** Light mode logo image URL. */
  logoLight?: string
  /** Dark mode logo image URL. */
  logoDark?: string
  /** Whether to render the site name text next to the logo. */
  showSiteNameText?: boolean
  /** Logo width in pixels. */
  logoWidth?: number
  /** Logo height in pixels. */
  logoHeight?: number
}

/** Theme layout for JavaScript. */
export interface JsThemeLayout {
  /** Sidebar width (CSS value). */
  sidebarWidth?: string
  /** Header height (CSS value). */
  headerHeight?: string
  /** Maximum content width (CSS value). */
  maxContentWidth?: string
}

/** Transform options for JavaScript. */
export interface JsTransformOptions {
  /** Enable GFM extensions. */
  gfm?: boolean
  /** Enable footnotes. */
  footnotes?: boolean
  /** Enable task lists. */
  taskLists?: boolean
  /** Enable tables. */
  tables?: boolean
  /** Enable strikethrough. */
  strikethrough?: boolean
  /** Enable autolinks. */
  autolinks?: boolean
  /** Maximum TOC depth (1-6). */
  tocMaxDepth?: number
  /** Convert `.md` links to `.html` links for SSG output. */
  convertMdLinks?: boolean
  /** Base URL for absolute link conversion (e.g., "/" or "/docs/"). */
  baseUrl?: string
  /** Source file path for relative link resolution. */
  sourcePath?: string
  /** Enable line annotations for code blocks using fence meta. */
  codeAnnotations?: boolean
  /** Fence meta key used to read code annotations. */
  codeAnnotationMetaKey?: string
  /** Code annotation syntax mode. */
  codeAnnotationSyntax?: string
  /** Enable line numbers for all code blocks by default. */
  codeAnnotationDefaultLineNumbers?: boolean
}

export declare function lintMarkdown(source: string, options?: JsMarkdownLintOptions | undefined | null): JsMarkdownLintResult

export declare function lintMarkdownDocuments(sources: Array<string>, options?: JsMarkdownLintOptions | undefined | null): Array<JsMarkdownLintResult>

/**
 * Loads dictionaries from the given directory.
 *
 * The directory should contain locale subdirectories (e.g., `en/`, `ja/`)
 * with JSON or YAML translation files.
 */
export declare function loadDictionaries(dir: string): I18NLoadResult

/**
 * Loads dictionaries from the given directory and returns a flat key-value map per locale.
 *
 * Each locale maps to a flat `{ "namespace.key": "value" }` structure.
 * Supports both JSON and YAML dictionary files.
 */
export declare function loadDictionariesFlat(dir: string): Record<string, Record<string, string>>

/** Restores code block metadata after JavaScript-side syntax highlighting. */
export declare function mergeHighlightedCodeBlocks(originalHtml: string, highlightedHtml: string): string

/** Mermaid transform result. */
export interface MermaidTransformResult {
  /** The transformed HTML with mermaid code blocks replaced by rendered SVGs. */
  html: string
  /** Non-fatal errors encountered during rendering (per-diagram). */
  errors: Array<string>
}

/** Result of MF2 validation. */
export interface Mf2ValidateResult {
  /** Whether the message is valid. */
  valid: boolean
  /** Validation errors. */
  errors: Array<string>
  /** AST as JSON (if parsing succeeded). */
  astJson?: string
}

/**
 * Parses Markdown source into an AST.
 *
 * Returns the AST as a JSON string for zero-copy transfer to JavaScript.
 */
export declare function parse(source: string, options?: JsParserOptions | undefined | null): ParseResult

/** Parses Markdown and renders to HTML. */
export declare function parseAndRender(source: string, options?: JsParserOptions | undefined | null): RenderResult

/** Parses Markdown and renders to HTML asynchronously (runs on worker thread). */
export declare function parseAndRenderAsync(source: string, options?: JsParserOptions | undefined | null): Promise<unknown>

/** Parses a Markdown slide deck with optional frontmatter and `---` separators. */
export declare function parseMarkdownSlideDeck(source: string, separator?: string | undefined | null): JsParsedSlideDeck

/** Parse result containing the AST as JSON. */
export interface ParseResult {
  /** The AST as a JSON string. */
  ast: string
  /** Parse errors, if any. */
  errors: Array<string>
}

/** Renders an AST (provided as JSON) to HTML. */
export declare function render(astJson: string): RenderResult

/** Render result containing the HTML output. */
export interface RenderResult {
  /** The rendered HTML. */
  html: string
  /** Render errors, if any. */
  errors: Array<string>
}

/**
 * Searches a serialized index.
 *
 * Takes a JSON-serialized index, query string, and options.
 * Returns an array of search results.
 */
export declare function searchIndex(indexJson: string, query: string, options?: JsSearchOptions | undefined | null): Array<JsSearchResult>

/** Table of contents entry. */
export interface TocEntry {
  /** Heading depth (1-6). */
  depth: number
  /** Heading text. */
  text: string
  /** URL-friendly slug. */
  slug: string
}

/**
 * Transforms Markdown source into HTML, frontmatter, and TOC.
 *
 * This is the main entry point for @ox-content/unplugin.
 */
export declare function transform(source: string, options?: JsTransformOptions | undefined | null): TransformResult

/** Transforms Markdown source asynchronously (runs on worker thread). */
export declare function transformAsync(source: string, options?: JsTransformOptions | undefined | null): Promise<unknown>

/**
 * Transforms mermaid code blocks in HTML to rendered SVG diagrams.
 *
 * Extracts `<pre><code class="language-mermaid">...</code></pre>` blocks,
 * renders each in parallel using the mmdc CLI, and replaces them with
 * `<div class="ox-mermaid">...</div>`.
 */
export declare function transformMermaid(html: string, mmdcPath: string): MermaidTransformResult

/** Transform result containing HTML, frontmatter, and TOC. */
export interface TransformResult {
  /** The rendered HTML. */
  html: string
  /** Parsed frontmatter as JSON string. */
  frontmatter: string
  /** Table of contents entries. */
  toc: Array<TocEntry>
  /** Parse/render errors, if any. */
  errors: Array<string>
}

/**
 * Validates an MF2 message string.
 *
 * Returns parsing and semantic validation results.
 */
export declare function validateMf2(message: string): Mf2ValidateResult

/** Returns the version of ox_content_napi. */
export declare function version(): string
