/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Parse result containing the AST as JSON. */
export interface ParseResult {
  /** The AST as a JSON string. */
  ast: string
  /** Parse errors, if any. */
  errors: Array<string>
}
/** Render result containing the HTML output. */
export interface RenderResult {
  /** The rendered HTML. */
  html: string
  /** Render errors, if any. */
  errors: Array<string>
}
/** Table of contents entry. */
export interface TocEntry {
  /** Heading depth (1-6). */
  depth: number
  /** Heading text. */
  text: string
  /** URL-friendly slug. */
  slug: string
}
/** Transform result containing HTML, frontmatter, and TOC. */
export interface TransformResult {
  /** The rendered HTML. */
  html: string
  /** Parsed frontmatter as JSON string. */
  frontmatter: string
  /** Table of contents entries. */
  toc: Array<TocEntry>
  /** Parse/render errors, if any. */
  errors: Array<string>
}
/** Transform options for JavaScript. */
export interface JsTransformOptions {
  /** Enable GFM extensions. */
  gfm?: boolean
  /** Enable footnotes. */
  footnotes?: boolean
  /** Enable task lists. */
  taskLists?: boolean
  /** Enable tables. */
  tables?: boolean
  /** Enable strikethrough. */
  strikethrough?: boolean
  /** Enable autolinks. */
  autolinks?: boolean
  /** Maximum TOC depth (1-6). */
  tocMaxDepth?: number
  /** Convert `.md` links to `.html` links for SSG output. */
  convertMdLinks?: boolean
  /** Base URL for absolute link conversion (e.g., "/" or "/docs/"). */
  baseUrl?: string
  /** Source file path for relative link resolution. */
  sourcePath?: string
}
/** Parser options for JavaScript. */
export interface JsParserOptions {
  /** Enable GFM extensions. */
  gfm?: boolean
  /** Enable footnotes. */
  footnotes?: boolean
  /** Enable task lists. */
  taskLists?: boolean
  /** Enable tables. */
  tables?: boolean
  /** Enable strikethrough. */
  strikethrough?: boolean
  /** Enable autolinks. */
  autolinks?: boolean
}
/**
 * Parses Markdown source into an AST.
 *
 * Returns the AST as a JSON string for zero-copy transfer to JavaScript.
 */
export declare function parse(source: string, options?: JsParserOptions | undefined | null): ParseResult
/** Parses Markdown and renders to HTML. */
export declare function parseAndRender(source: string, options?: JsParserOptions | undefined | null): RenderResult
/** Renders an AST (provided as JSON) to HTML. */
export declare function render(astJson: string): RenderResult
/** Returns the version of ox_content_napi. */
export declare function version(): string
/**
 * Transforms Markdown source into HTML, frontmatter, and TOC.
 *
 * This is the main entry point for unplugin-ox-content.
 */
export declare function transform(source: string, options?: JsTransformOptions | undefined | null): TransformResult
/** Parses Markdown and renders to HTML asynchronously (runs on worker thread). */
export declare function parseAndRenderAsync(source: string, options?: JsParserOptions | undefined | null): Promise<unknown>
/** Transforms Markdown source asynchronously (runs on worker thread). */
export declare function transformAsync(source: string, options?: JsTransformOptions | undefined | null): Promise<unknown>
/** OG image configuration for JavaScript. */
export interface JsOgImageConfig {
  /** Image width in pixels. */
  width?: number
  /** Image height in pixels. */
  height?: number
  /** Background color (hex). */
  backgroundColor?: string
  /** Text color (hex). */
  textColor?: string
  /** Title font size. */
  titleFontSize?: number
  /** Description font size. */
  descriptionFontSize?: number
}
/** OG image data for JavaScript. */
export interface JsOgImageData {
  /** Page title. */
  title: string
  /** Page description. */
  description?: string
  /** Site name. */
  siteName?: string
  /** Author name. */
  author?: string
}
/**
 * Generates an OG image as SVG.
 *
 * This function generates an SVG representation of an OG image
 * that can be used for social media previews.
 */
export declare function generateOgImageSvg(data: JsOgImageData, config?: JsOgImageConfig | undefined | null): string
/** Search document for JavaScript. */
export interface JsSearchDocument {
  /** Unique document identifier. */
  id: string
  /** Document title. */
  title: string
  /** Document URL. */
  url: string
  /** Document body text. */
  body: string
  /** Document headings. */
  headings: Array<string>
  /** Code snippets. */
  code: Array<string>
}
/** Search result for JavaScript. */
export interface JsSearchResult {
  /** Document ID. */
  id: string
  /** Document title. */
  title: string
  /** Document URL. */
  url: string
  /** Relevance score. */
  score: number
  /** Matched terms. */
  matches: Array<string>
  /** Content snippet. */
  snippet: string
}
/** Search options for JavaScript. */
export interface JsSearchOptions {
  /** Maximum number of results. */
  limit?: number
  /** Enable prefix matching. */
  prefix?: boolean
  /** Enable fuzzy matching. */
  fuzzy?: boolean
  /** Minimum score threshold. */
  threshold?: number
}
/**
 * Builds a search index from documents.
 *
 * Takes an array of documents and returns a serialized search index as JSON.
 */
export declare function buildSearchIndex(documents: Array<JsSearchDocument>): string
/**
 * Searches a serialized index.
 *
 * Takes a JSON-serialized index, query string, and options.
 * Returns an array of search results.
 */
export declare function searchIndex(indexJson: string, query: string, options?: JsSearchOptions | undefined | null): Array<JsSearchResult>
/** Navigation item for SSG. */
export interface JsSsgNavItem {
  /** Display title. */
  title: string
  /** URL path. */
  path: string
  /** Full href. */
  href: string
}
/** Navigation group for SSG. */
export interface JsSsgNavGroup {
  /** Group title. */
  title: string
  /** Navigation items. */
  items: Array<JsSsgNavItem>
}
/** Hero action for entry page. */
export interface JsHeroAction {
  /** Button theme: "brand" or "alt". */
  theme?: string
  /** Button text. */
  text: string
  /** Link URL. */
  link: string
}
/** Hero image for entry page. */
export interface JsHeroImage {
  /** Image source URL. */
  src: string
  /** Alt text. */
  alt?: string
  /** Image width. */
  width?: number
  /** Image height. */
  height?: number
}
/** Hero section configuration for entry page. */
export interface JsHeroConfig {
  /** Main title (large, gradient text). */
  name?: string
  /** Secondary text. */
  text?: string
  /** Tagline. */
  tagline?: string
  /** Hero image. */
  image?: JsHeroImage
  /** Action buttons. */
  actions?: Array<JsHeroAction>
}
/** Feature card for entry page. */
export interface JsFeatureConfig {
  /** Icon - supports: "mdi:icon-name" (Iconify), image URL, or emoji. */
  icon?: string
  /** Feature title. */
  title: string
  /** Feature description. */
  details?: string
  /** Optional link. */
  link?: string
  /** Link text. */
  linkText?: string
}
/** Entry page configuration. */
export interface JsEntryPageConfig {
  /** Hero section. */
  hero?: JsHeroConfig
  /** Feature cards. */
  features?: Array<JsFeatureConfig>
}
/** Page data for SSG. */
export interface JsSsgPageData {
  /** Page title. */
  title: string
  /** Page description. */
  description?: string
  /** Page content HTML. */
  content: string
  /** Table of contents entries. */
  toc: Array<TocEntry>
  /** URL path. */
  path: string
  /** Entry page configuration (if layout: entry). */
  entryPage?: JsEntryPageConfig
}
/** Theme colors for JavaScript. */
export interface JsThemeColors {
  /** Primary accent color. */
  primary?: string
  /** Primary color on hover. */
  primaryHover?: string
  /** Background color. */
  background?: string
  /** Alternative background color. */
  backgroundAlt?: string
  /** Main text color. */
  text?: string
  /** Muted text color. */
  textMuted?: string
  /** Border color. */
  border?: string
  /** Code block background color. */
  codeBackground?: string
  /** Code block text color. */
  codeText?: string
}
/** Theme fonts for JavaScript. */
export interface JsThemeFonts {
  /** Sans-serif font stack. */
  sans?: string
  /** Monospace font stack. */
  mono?: string
}
/** Theme layout for JavaScript. */
export interface JsThemeLayout {
  /** Sidebar width (CSS value). */
  sidebarWidth?: string
  /** Header height (CSS value). */
  headerHeight?: string
  /** Maximum content width (CSS value). */
  maxContentWidth?: string
}
/** Theme header for JavaScript. */
export interface JsThemeHeader {
  /** Logo image URL. */
  logo?: string
  /** Logo width in pixels. */
  logoWidth?: number
  /** Logo height in pixels. */
  logoHeight?: number
}
/** Theme footer for JavaScript. */
export interface JsThemeFooter {
  /** Footer message (supports HTML). */
  message?: string
  /** Copyright text (supports HTML). */
  copyright?: string
}
/** Social links for JavaScript. */
export interface JsSocialLinks {
  /** GitHub URL. */
  github?: string
  /** Twitter/X URL. */
  twitter?: string
  /** Discord URL. */
  discord?: string
}
/** Embedded HTML content for specific positions. */
export interface JsThemeEmbed {
  /** Content to embed into <head>. */
  head?: string
  /** Content before header. */
  headerBefore?: string
  /** Content after header. */
  headerAfter?: string
  /** Content before sidebar navigation. */
  sidebarBefore?: string
  /** Content after sidebar navigation. */
  sidebarAfter?: string
  /** Content before main content. */
  contentBefore?: string
  /** Content after main content. */
  contentAfter?: string
  /** Content before footer. */
  footerBefore?: string
  /** Custom footer content. */
  footer?: string
}
/** Theme configuration for JavaScript. */
export interface JsThemeConfig {
  /** Light mode colors. */
  colors?: JsThemeColors
  /** Dark mode colors. */
  darkColors?: JsThemeColors
  /** Font configuration. */
  fonts?: JsThemeFonts
  /** Layout configuration. */
  layout?: JsThemeLayout
  /** Header configuration. */
  header?: JsThemeHeader
  /** Footer configuration. */
  footer?: JsThemeFooter
  /** Social links configuration. */
  socialLinks?: JsSocialLinks
  /** Embedded HTML content at specific positions. */
  embed?: JsThemeEmbed
  /** Additional custom CSS. */
  css?: string
  /** Additional custom JavaScript. */
  js?: string
}
/** SSG configuration. */
export interface JsSsgConfig {
  /** Site name. */
  siteName: string
  /** Base URL path. */
  base: string
  /** OG image URL. */
  ogImage?: string
  /** Theme configuration. */
  theme?: JsThemeConfig
}
/** Generates SSG HTML page with navigation and search. */
export declare function generateSsgHtml(pageData: JsSsgPageData, navGroups: Array<JsSsgNavGroup>, config: JsSsgConfig): string
/**
 * Extracts searchable content from Markdown source.
 *
 * Parses the Markdown and extracts title, body text, headings, and code.
 */
export declare function extractSearchContent(source: string, id: string, url: string, options?: JsParserOptions | undefined | null): JsSearchDocument
/** Mermaid render options for JavaScript. */
export interface JsMermaidOptions {
  /** Mermaid theme: default, dark, forest, neutral, base. */
  theme?: string
  /** Background color for the diagram. */
  backgroundColor?: string
}
/** Mermaid render result. */
export interface MermaidResult {
  /** The rendered SVG string. */
  svg: string
  /** Error message if rendering failed. */
  error?: string
}
/**
 * Renders a mermaid diagram to SVG using mmdc (mermaid-cli).
 *
 * Requires @mermaid-js/mermaid-cli to be installed.
 */
export declare function renderMermaid(code: string, options?: JsMermaidOptions | undefined | null): MermaidResult
/**
 * Renders a mermaid diagram to SVG asynchronously (runs on worker thread).
 *
 * Requires @mermaid-js/mermaid-cli to be installed.
 */
export declare function renderMermaidAsync(code: string, options?: JsMermaidOptions | undefined | null): Promise<unknown>
