packages:
  - crates/ox_content_napi
  - crates/ox_content_wasm/pkg
  - npm/*
  - docs
  - examples/*
  - benchmarks/*
  - benchmarks/bundle-size/apps/*

catalog:
  "@sveltejs/vite-plugin-svelte": ^7.0.0
  "@types/node": ^22.0.0
  "@types/react": ^19.0.0
  "@types/react-dom": ^19.0.0
  "@vitejs/plugin-react": ^6.0.0
  "@vitejs/plugin-vue": ^6.0.0
  "@typescript/native-preview": ^7.0.0-dev.20250601
  esbuild: ^0.27.4
  react: ^19.0.0
  react-dom: ^19.0.0
  svelte: ^5.46.4
  typescript: ^5.7.0
  vite: npm:@voidzero-dev/vite-plus-core@0.1.11
  vitest: npm:@voidzero-dev/vite-plus-test@0.1.11
  vue: ^3.5.0
  vite-plus: 0.1.11

onlyBuiltDependencies:
  - esbuild
  - sharp
  - puppeteer
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
