packages:
  - crates/ox_content_napi
  - crates/ox_content_wasm/pkg
  - npm/*
  - docs
  - examples/*
  - benchmarks/*
  - benchmarks/bundle-size/apps/*

catalog:
  '@sveltejs/vite-plugin-svelte': ^5.0.0
  '@types/node': ^22.0.0
  '@types/react': ^19.0.0
  '@types/react-dom': ^19.0.0
  '@vitejs/plugin-react': ^4.0.0
  '@vitejs/plugin-vue': ^5.2.0
  oxlint: ^1.0.0
  react: ^19.0.0
  react-dom: ^19.0.0
  svelte: ^5.0.0
  tsup: ^8.0.0
  typescript: ^5.7.0
  vite: ^7.0.0
  vue: ^3.5.0

onlyBuiltDependencies:
  - esbuild
  - sharp
