packages:
  # NAPI bindings
  - 'crates/ox_content_napi'
  # WASM bindings
  - 'crates/ox_content_wasm/pkg'
  # JavaScript packages
  - 'packages/*'
  # Documentation
  - 'docs'
  # Examples
  - 'examples/*'
  # Benchmarks
  - 'benchmarks/*'
  - 'benchmarks/bundle-size/apps/*'

catalog:
  # Build tools
  vite: ^7.0.0
  tsup: ^8.0.0
  typescript: ^5.7.0
  oxlint: ^1.0.0

  # Vue
  vue: ^3.5.0
  '@vitejs/plugin-vue': ^5.2.0

  # React
  react: ^19.0.0
  react-dom: ^19.0.0
  '@vitejs/plugin-react': ^4.0.0
  '@types/react': ^19.0.0
  '@types/react-dom': ^19.0.0

  # Svelte
  svelte: ^5.0.0
  '@sveltejs/vite-plugin-svelte': ^5.0.0

  # Types
  '@types/node': ^22.0.0

onlyBuiltDependencies:
  - esbuild
