use napi::bindgen_prelude::Either;
use ox_content_transform::{MathOptions, TransformOptions};

use super::JsTransformOptions;

impl From<JsTransformOptions> for TransformOptions {
    fn from(value: JsTransformOptions) -> Self {
        Self {
            gfm: value.gfm,
            mdx: value.mdx,
            footnotes: value.footnotes,
            semantic_footnotes: value.semantic_footnotes,
            task_lists: value.task_lists,
            tables: value.tables,
            strikethrough: value.strikethrough,
            autolinks: value.autolinks,
            superscript: value.superscript,
            subscript: value.subscript,
            smart_punctuation: value.smart_punctuation,
            frontmatter: value.frontmatter,
            toc_max_depth: value.toc_max_depth,
            convert_md_links: value.convert_md_links,
            base_url: value.base_url,
            source_path: value.source_path,
            code_annotations: value.code_annotations,
            code_annotation_meta_key: value.code_annotation_meta_key,
            code_annotation_syntax: value.code_annotation_syntax,
            code_annotation_default_line_numbers: value.code_annotation_default_line_numbers,
            autolink_urls: value.autolink_urls,
            autolink_patterns: value.autolink_patterns,
            autolink_target_blank: value.autolink_target_blank,
            link_target_blank: value.link_target_blank,
            source_spans: value.source_spans,
            heading_permalinks: value.heading_permalinks,
            wiki_links: value.wiki_links.map(Into::into),
            emoji_shortcodes: value.emoji_shortcodes.map(Into::into),
            attributes: value.attributes.map(Into::into),
            cjk_emphasis: value.cjk_emphasis,
            code_imports: value.code_imports.map(Into::into),
            sanitize: value.sanitize.map(Into::into),
            edit_this_page: value.edit_this_page.map(Into::into),
            containers: value.containers.map(Into::into),
            includes: value.includes.map(Into::into),
            partials: value.partials.map(Into::into),
            steps: value.steps.map(Into::into),
            code_groups: value.code_groups.map(Into::into),
            badges: value.badges.map(Into::into),
            not_by_ai: value.not_by_ai.map(Into::into),
            keyboard_keys: value.keyboard_keys.map(Into::into),
            abbreviations: value.abbreviations.map(Into::into),
            definition_lists: value.definition_lists.map(Into::into),
            magic_links: value.magic_links.map(Into::into),
            images: value.images.map(Into::into),
            image_galleries: value.image_galleries.map(Into::into),
            timelines: value.timelines.map(Into::into),
            conditional_blocks: value.conditional_blocks.map(Into::into),
            cards: value.cards.map(Into::into),
            math: match value.math {
                Some(Either::A(enabled)) => Some(MathOptions { enabled: Some(enabled) }),
                Some(Either::B(options)) => Some(options.into()),
                None => None,
            },
            file_tree: value.file_tree.map(Into::into),
            data_tables: value.data_tables.map(Into::into),
        }
    }
}
