/**
 * Auto-generated API documentation navigation.
 * This file is automatically generated by the docs plugin.
 * Do not edit manually.
 */

export interface NavItem {
  title: string;
  path: string;
  children?: NavItem[];
}

export const apiNav: NavItem[] = [
  {
    "title": "Browser",
    "path": "/api/browser"
  },
  {
    "title": "Cache",
    "path": "/api/cache"
  },
  {
    "title": "Dev Server",
    "path": "/api/dev-server"
  },
  {
    "title": "Docs",
    "path": "/api/docs"
  },
  {
    "title": "Environment",
    "path": "/api/environment"
  },
  {
    "title": "Github",
    "path": "/api/github"
  },
  {
    "title": "Highlight",
    "path": "/api/highlight"
  },
  {
    "title": "I18n",
    "path": "/api/i18n"
  },
  {
    "title": "Jsx Runtime",
    "path": "/api/jsx-runtime"
  },
  {
    "title": "Lint",
    "path": "/api/lint"
  },
  {
    "title": "Lint Files",
    "path": "/api/lint-files"
  },
  {
    "title": "Mermaid",
    "path": "/api/mermaid"
  },
  {
    "title": "Mermaid Protect",
    "path": "/api/mermaid-protect"
  },
  {
    "title": "Nav Generator",
    "path": "/api/nav-generator"
  },
  {
    "title": "Ogp",
    "path": "/api/ogp"
  },
  {
    "title": "Overview",
    "path": "/api/index"
  },
  {
    "title": "Overview",
    "path": "/api/index"
  },
  {
    "title": "Overview",
    "path": "/api/index"
  },
  {
    "title": "Page Context",
    "path": "/api/page-context"
  },
  {
    "title": "Parse",
    "path": "/api/parse"
  },
  {
    "title": "Renderer",
    "path": "/api/renderer"
  },
  {
    "title": "Search",
    "path": "/api/search"
  },
  {
    "title": "Ssg",
    "path": "/api/ssg"
  },
  {
    "title": "Tabs",
    "path": "/api/tabs"
  },
  {
    "title": "Template",
    "path": "/api/template"
  },
  {
    "title": "Theme",
    "path": "/api/theme"
  },
  {
    "title": "Theme Renderer",
    "path": "/api/theme-renderer"
  },
  {
    "title": "Transform",
    "path": "/api/transform"
  },
  {
    "title": "Types",
    "path": "/api/types"
  },
  {
    "title": "Types",
    "path": "/api/types"
  },
  {
    "title": "Youtube",
    "path": "/api/youtube"
  }
] as const;
