/**
 * Auto-generated API documentation navigation.
 * This file is automatically generated by the docs plugin.
 * Do not edit manually.
 */

export interface NavItem {
  title: string;
  path: string;
  children?: NavItem[];
}

export const apiNav: NavItem[] = [
  {
    "title": "Docs",
    "path": "/api/docs"
  },
  {
    "title": "Environment",
    "path": "/api/environment"
  },
  {
    "title": "Highlight",
    "path": "/api/highlight"
  },
  {
    "title": "Jsx Runtime",
    "path": "/api/jsx-runtime"
  },
  {
    "title": "Jsx.d",
    "path": "/api/jsx.d"
  },
  {
    "title": "Mermaid",
    "path": "/api/mermaid"
  },
  {
    "title": "Nav Generator",
    "path": "/api/nav-generator"
  },
  {
    "title": "Overview",
    "path": "/api/index"
  },
  {
    "title": "Page Context",
    "path": "/api/page-context"
  },
  {
    "title": "Search",
    "path": "/api/search"
  },
  {
    "title": "Ssg",
    "path": "/api/ssg"
  },
  {
    "title": "Theme",
    "path": "/api/theme"
  },
  {
    "title": "Theme Renderer",
    "path": "/api/theme-renderer"
  },
  {
    "title": "Transform",
    "path": "/api/transform"
  },
  {
    "title": "Types",
    "path": "/api/types"
  }
] as const;
