/**
 * Navigation metadata generator for API documentation.
 *
 * Generates navigation structure from extracted documentation,
 * suitable for use in sidebar navigation components.
 */

import path from 'path';
import type { ExtractedDocs, NavItem } from './types';

/**
 * Generates navigation metadata from extracted documentation.
 *
 * Takes the extracted documentation array and produces a navigation structure
 * that can be imported into documentation sites.
 *
 * @param docs - Array of extracted documentation
 * @param basePath - Base path prefix for navigation items (default: '/api')
 * @returns Array of navigation items
 */
export function generateNavMetadata(docs: ExtractedDocs[], basePath: string = '/api'): NavItem[] {
  // Sort docs by filename for consistent ordering
  const sortedDocs = [...docs].sort((a, b) => {
    const aName = getDocDisplayName(a.file);
    const bName = getDocDisplayName(b.file);
    return aName.localeCompare(bName);
  });

  return sortedDocs.map((doc) => ({
    title: getDocDisplayName(doc.file),
    path: `${basePath}/${getDocFileName(doc.file)}`,
  }));
}

/**
 * Gets the display name for a documentation file.
 *
 * Converts file paths to friendly display names.
 * Example: '../packages/vite-plugin-ox-content/src/transform.ts' → 'Transform'
 *
 * @param filePath - Source file path
 * @returns Formatted display name
 */
function getDocDisplayName(filePath: string): string {
  const fileName = path.basename(filePath, path.extname(filePath));
  // Handle special cases
  if (fileName === 'index' || fileName === 'index-module') {
    return 'Overview';
  }
  // Convert camelCase/kebab-case to Title Case
  return fileName
    .replace(/[-_]([a-z])/g, (_, char) => ' ' + char.toUpperCase())
    .replace(/^[a-z]/, (char) => char.toUpperCase());
}

/**
 * Gets the file name to use in navigation paths.
 *
 * @param filePath - Source file path
 * @returns File name without extension
 */
function getDocFileName(filePath: string): string {
  const fileName = path.basename(filePath, path.extname(filePath));
  // Handle filename conflicts (index is renamed to index-module by docs generator)
  if (fileName === 'index') {
    return 'index';
  }
  return fileName;
}

/**
 * Generates TypeScript code for navigation export.
 *
 * Creates TypeScript code that exports the navigation structure as a const,
 * suitable for static imports in Vue/React components.
 *
 * @param navItems - Navigation items to export
 * @param exportName - Name of the exported constant (default: 'apiNav')
 * @returns TypeScript code as string
 */
export function generateNavCode(navItems: NavItem[], exportName: string = 'apiNav'): string {
  const json = JSON.stringify(navItems, null, 2);
  return `/**
 * Auto-generated API documentation navigation.
 * This file is automatically generated by the docs plugin.
 * Do not edit manually.
 */

export interface NavItem {
  title: string;
  path: string;
  children?: NavItem[];
}

export const ${exportName}: NavItem[] = ${json} as const;
`;
}
