/**
 * Auto-generated API documentation navigation.
 * This file is automatically generated by the docs plugin.
 * Do not edit manually.
 */

export interface NavItem {
  title: string;
  path: string;
  children?: NavItem[];
}

export const apiNav: NavItem[] = [
  {
    "title": "Math",
    "path": "/api/math"
  },
  {
    "title": "Utils",
    "path": "/api/utils"
  }
] as const;
